Repository zzerogu/cnumap, pull requests merged in 2024-12, with the labels that each got.

#7 [Init/FE] 초기 코드 재업로드 & 테스트용 로그인 코드 추가 & Mapbox 테스트
  .github/ISSUE_TEMPLATE/기능-세팅-템플릿.md
  .github/ISSUE_TEMPLATE/버그-기록-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  frontend/.DS_Store
  frontend/moducnu/.gitignore
  frontend/moducnu/ios/Flutter/Debug.xcconfig
  frontend/moducnu/ios/Flutter/Release.xcconfig
  frontend/moducnu/ios/Podfile
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/ios/Runner.xcodeproj/project.pbxproj
  frontend/moducnu/ios/Runner.xcworkspace/contents.xcworkspacedata
  frontend/moducnu/lib/data/mapper/auth_mapper.dart
  frontend/moducnu/lib/data/remote/api/.gitkeep
  frontend/moducnu/lib/data/remote/api/auth/auth_api.dart
  frontend/moducnu/lib/data/remote/api/auth/auth_api.g.dart
  frontend/moducnu/lib/data/remote/api/map/map_api.dart
  frontend/moducnu/lib/data/remote/api/parse_error_loger.dart
  frontend/moducnu/lib/data/remote/api/place/place_api.dart
  frontend/moducnu/lib/data/remote/dto/.gitkeep
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.dart
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.g.dart
  frontend/moducnu/lib/data/repository/.gitkeep
  frontend/moducnu/lib/data/repository/auth_repositoryimpl.dart
  frontend/moducnu/lib/di/auth_di.dart
  frontend/moducnu/lib/di/network_di.dart
  frontend/moducnu/lib/di/service_locator.dart
  frontend/moducnu/lib/domain/model/.gitkeep
  frontend/moducnu/lib/domain/model/User.dart
  frontend/moducnu/lib/domain/repository/.gitkeep
  frontend/moducnu/lib/domain/repository/auth_repository.dart
  frontend/moducnu/lib/domain/usecases/.gitkeep
  frontend/moducnu/lib/domain/usecases/auto_login_usecase.dart
  frontend/moducnu/lib/domain/usecases/login_usecase.dart
  frontend/moducnu/lib/domain/usecases/signup_usecase.dart
  frontend/moducnu/lib/main.dart
  frontend/moducnu/lib/navigation/main_navigation_page.dart
  frontend/moducnu/lib/presentation/auth/login_page.dart
  frontend/moducnu/lib/presentation/auth/login_viewmodel.dart
  frontend/moducnu/lib/presentation/auth/signup_page.dart
  frontend/moducnu/lib/presentation/auth/signup_viewmodel.dart
  frontend/moducnu/lib/presentation/common/custom_btn.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/mappage.dart
  frontend/moducnu/lib/presentation/saved/save_page.dart
  frontend/moducnu/lib/presentation/school/school_page.dart
  frontend/moducnu/lib/presentation/theme/color.dart
  frontend/moducnu/lib/presentation/timetable/time_page.dart
  frontend/moducnu/macos/Flutter/Flutter-Debug.xcconfig
  frontend/moducnu/macos/Flutter/Flutter-Release.xcconfig
  frontend/moducnu/macos/Podfile
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
Labels: 🐰 FE, 🐢 aengzu, ⚔️ Setting

#12 [Update/FE] FE 작업 코드 업데이트
  frontend/.DS_Store
  frontend/moducnu/.gitignore
  frontend/moducnu/ios/Flutter/Debug.xcconfig
  frontend/moducnu/ios/Flutter/Release.xcconfig
  frontend/moducnu/ios/Podfile
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/ios/Runner.xcodeproj/project.pbxproj
  frontend/moducnu/ios/Runner.xcworkspace/contents.xcworkspacedata
  frontend/moducnu/lib/data/mapper/auth_mapper.dart
  frontend/moducnu/lib/data/remote/api/.gitkeep
  frontend/moducnu/lib/data/remote/api/auth/auth_api.dart
  frontend/moducnu/lib/data/remote/api/auth/auth_api.g.dart
  frontend/moducnu/lib/data/remote/api/map/map_api.dart
  frontend/moducnu/lib/data/remote/api/parse_error_loger.dart
  frontend/moducnu/lib/data/remote/api/place/place_api.dart
  frontend/moducnu/lib/data/remote/dto/.gitkeep
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.dart
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.g.dart
  frontend/moducnu/lib/data/repository/.gitkeep
  frontend/moducnu/lib/data/repository/auth_repositoryimpl.dart
  frontend/moducnu/lib/di/auth_di.dart
  frontend/moducnu/lib/di/network_di.dart
  frontend/moducnu/lib/di/service_locator.dart
  frontend/moducnu/lib/domain/model/.gitkeep
  frontend/moducnu/lib/domain/model/User.dart
  frontend/moducnu/lib/domain/repository/.gitkeep
  frontend/moducnu/lib/domain/repository/auth_repository.dart
  frontend/moducnu/lib/domain/usecases/.gitkeep
  frontend/moducnu/lib/domain/usecases/auto_login_usecase.dart
  frontend/moducnu/lib/domain/usecases/login_usecase.dart
  frontend/moducnu/lib/domain/usecases/signup_usecase.dart
  frontend/moducnu/lib/main.dart
  frontend/moducnu/lib/navigation/main_navigation_page.dart
  frontend/moducnu/lib/presentation/auth/login_page.dart
  frontend/moducnu/lib/presentation/auth/login_viewmodel.dart
  frontend/moducnu/lib/presentation/auth/signup_page.dart
  frontend/moducnu/lib/presentation/auth/signup_viewmodel.dart
  frontend/moducnu/lib/presentation/common/custom_btn.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/mappage.dart
  frontend/moducnu/lib/presentation/saved/save_page.dart
  frontend/moducnu/lib/presentation/school/school_page.dart
  frontend/moducnu/lib/presentation/theme/color.dart
  frontend/moducnu/lib/presentation/timetable/time_page.dart
  frontend/moducnu/macos/Flutter/Flutter-Debug.xcconfig
  frontend/moducnu/macos/Flutter/Flutter-Release.xcconfig
  frontend/moducnu/macos/Podfile
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
Labels: 🗳️ Update

#25 [Fix/FE] 안드로이드 빌드 오류 수정
  frontend/moducnu/.gitignore
  frontend/moducnu/android/gradle/wrapper/gradle-wrapper.properties
  frontend/moducnu/android/settings.gradle
  frontend/moducnu/lib/main.dart
Labels: 🐞 BugFix, 🐰 FE

#26 [Design/FE] Bottomsheet design
  .gitignore
  frontend/moducnu/.gitignore
  frontend/moducnu/assets/icons/Close.png
  frontend/moducnu/assets/icons/Favorite.png
  frontend/moducnu/assets/icons/Phone.png
  frontend/moducnu/assets/icons/Place Marker.png
  frontend/moducnu/assets/icons/Route.png
  frontend/moducnu/assets/icons/Share Rounded.png
  frontend/moducnu/assets/icons/Wheelchair user.png
  frontend/moducnu/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  frontend/moducnu/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  frontend/moducnu/lib/data/local/entity/location_data.dart
  frontend/moducnu/lib/presentation/common/modal_bottom_sheet.dart
  frontend/moducnu/linux/flutter/generated_plugins.cmake
  frontend/moducnu/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  frontend/moducnu/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  frontend/moducnu/macos/Runner.xcworkspace/contents.xcworkspacedata
  frontend/moducnu/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  frontend/moducnu/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  frontend/moducnu/web/manifest.json
  frontend/moducnu/windows/flutter/generated_plugins.cmake
Labels: 🐰 FE, 🐳 young, 🎨 Design

#30 [Api/FE] Swagger 기반 API 호출 코드 업로드
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/api/construction/construction_api.dart
  frontend/moducnu/lib/data/remote/api/construction/construction_api.g.dart
  frontend/moducnu/lib/data/remote/api/disabled_restroom/disabled_restroom_api.dart
  frontend/moducnu/lib/data/remote/api/disabled_restroom/disabled_restroom_api.g.dart
  frontend/moducnu/lib/data/remote/api/map/map_api.dart
  frontend/moducnu/lib/data/remote/api/map/map_api.g.dart
  frontend/moducnu/lib/data/remote/api/navigation/navigation_api.dart
  frontend/moducnu/lib/data/remote/api/navigation/navigation_api.g.dart
  frontend/moducnu/lib/data/remote/api/node/node_api.dart
  frontend/moducnu/lib/data/remote/api/node/node_api.g.dart
  frontend/moducnu/lib/data/remote/api/place/place_api.dart
  frontend/moducnu/lib/data/remote/api/ramp/ramp_api.dart
  frontend/moducnu/lib/data/remote/api/ramp/ramp_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/construction/construction_dto.dart
  frontend/moducnu/lib/data/remote/dto/construction/construction_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/disabled_restroom/disabled_restroom_dto.dart
  frontend/moducnu/lib/data/remote/dto/disabled_restroom/disabled_restroom_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/navigation/navigation_dto.dart
  frontend/moducnu/lib/data/remote/dto/navigation/navigation_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/node/node_dto.dart
  frontend/moducnu/lib/data/remote/dto/node/node_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/ramp/ramp_dto.dart
  frontend/moducnu/lib/data/remote/dto/ramp/ramp_dto.g.dart
  frontend/moducnu/lib/presentation/common/custom_search_bar.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/search_page.dart
  frontend/moducnu/pubspec.lock
Labels: 🐰 FE, 🐢 aengzu, 📬 API
