Repository zzerogu/cnumap, pull requests merged in 2025-01, with the labels that each got.

#34 [Chore/BE] 네비게이션 알고리즘 세팅 & docker test
  backend/rust_server/Dockerfile
  backend/valhalla_server/duplicateways.txt
  backend/valhalla_server/tiles/2/000/728/429.gph
  backend/valhalla_server/valhalla/build/CMakeFiles/3.31.2/CMakeDetermineCompilerABI_C.bin
  backend/valhalla_server/valhalla/build/CMakeFiles/3.31.2/CMakeDetermineCompilerABI_CXX.bin
  backend/valhalla_server/valhalla/build/CMakeFiles/CMakeConfigureLog.yaml
  backend/valhalla_server/valhalla/build/CMakeFiles/Makefile2
  backend/valhalla_server/valhalla/build/lib/libgmock.a
  backend/valhalla_server/valhalla/build/lib/libgmock_main.a
  backend/valhalla_server/valhalla/build/lib/libgtest.a
  backend/valhalla_server/valhalla/build/lib/libgtest_main.a
  backend/valhalla_server/valhalla/src/sif/wheelchair_cost.cc
Labels: 🐧 BE, 📬 API

#35 [Design/FE] School Tab 및 Category 컴포넌트 디자인
  frontend/moducnu/lib/navigation/main_navigation_page.dart
  frontend/moducnu/lib/presentation/common/category_chip.dart
  frontend/moducnu/lib/presentation/common/category_list.dart
  frontend/moducnu/lib/presentation/common/custom_search_bar.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/search_page.dart
  frontend/moducnu/lib/presentation/school/component/building_info_section.dart
  frontend/moducnu/lib/presentation/school/component/chacha_info_section.dart
  frontend/moducnu/lib/presentation/school/component/section_title.dart
  frontend/moducnu/lib/presentation/school/school_page.dart
  frontend/moducnu/lib/presentation/theme/color.dart
Labels: 🐰 FE, 🐢 aengzu, 🎨 Design

#39 [Fix/FE] Merge Conflict 해결
  frontend/moducnu/lib/presentation/common/custom_bottom.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
Labels: 🐞 BugFix, 🐰 FE

#40 [BE & FE] 백앤드 api 추가 및 프론트 build api 추가 및 dto 추가. 클릭 이벤트 진행중
  .gitignore
  backend/docker-compose.yml
  backend/rust_server/src/handlers/building.rs
  backend/rust_server/src/main.rs
  backend/rust_server/src/routes/building.rs
  backend/tegola_server/config.toml
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/lib/data/remote/api/building/building_api.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/presentation/common/map_component.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
Labels: 🐧 BE, 🐰 FE, 🦖 zungu, 📬 API

#44 [Feat/FE] 마커 + 네비게이션 구현
  backend/docker-compose.yml
  backend/rust_server/Dockerfile
  backend/rust_server/src/handlers/navigation.rs
  backend/rust_server/src/main.rs
  backend/rust_server/src/routes/navigation.rs
  backend/valhalla_server/duplicateways.txt
  backend/valhalla_server/tiles.tar
  backend/valhalla_server/tiles/2/000/728/429.gph
  backend/valhalla_server/valhalla.json
  frontend/moducnu/android/app/src/main/AndroidManifest.xml
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/ios/Runner.xcodeproj/project.pbxproj
  frontend/moducnu/ios/Runner/Info.plist
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/api/disabled_restroom/disabled_restroom_api.dart
  frontend/moducnu/lib/data/remote/api/disabled_restroom/disabled_restroom_api.g.dart
  frontend/moducnu/lib/data/remote/api/map/map_api.dart
  frontend/moducnu/lib/data/remote/api/navigation/navigation_api.dart
  frontend/moducnu/lib/data/remote/api/navigation/navigation_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/disabled_restroom/disabled_restroom_dto.dart
  frontend/moducnu/lib/data/remote/dto/disabled_restroom/disabled_restroom_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/navigation/navigation_dto.dart
  frontend/moducnu/lib/data/remote/dto/navigation/navigation_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/ramp/ramp_dto.dart
  frontend/moducnu/lib/data/remote/dto/ramp/ramp_dto.g.dart
  frontend/moducnu/lib/presentation/common/building_detail_popup.dart
  frontend/moducnu/lib/presentation/common/category_list.dart
  frontend/moducnu/lib/presentation/common/map_component.dart
  frontend/moducnu/lib/presentation/common/route_finder_modal.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
  frontend/moducnu/windows/flutter/generated_plugin_registrant.cc
Labels: 🐧 BE, 🐰 FE, 📬 API, 🗳️ Update

#47 [Feat/FE] 공사 소식 관련 데이터 연결 (단, db에 더미데이터가 없기 때문에 일부 주석 처리)
  backend/rust_server/src/handlers/mod.rs
  backend/rust_server/src/handlers/ramp.rs
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/mapper/construction_mapper.dart
  frontend/moducnu/lib/data/repository/construction_repositoryImpl.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/construction_di.dart
  frontend/moducnu/lib/di/network_di.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/di/service_locator.dart
  frontend/moducnu/lib/domain/model/construction_news.dart
  frontend/moducnu/lib/domain/model/place.dart
  frontend/moducnu/lib/domain/repository/construction_repository.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/lib/domain/usecases/get_all_construction_news_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_latest_construction_news_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_place_by_name_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_place_detail_by_id.dart
  frontend/moducnu/lib/domain/usecases/get_places_by_category_usecase.dart
  frontend/moducnu/lib/presentation/common/custom_search_bar.dart
  frontend/moducnu/lib/presentation/common/place_item.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/search_page.dart
  frontend/moducnu/lib/presentation/map/search_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/construction_news_component.dart
  frontend/moducnu/lib/presentation/school/component/construction_news_viewmodel.dart
  frontend/moducnu/lib/presentation/school/school_page.dart
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature, 📬 API

#52 [Fix/FE] Dto 관련 에러 수정
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
Labels: 🐞 BugFix, 🐢 aengzu

#54 [Refactor/FE] 검색 기능 강화
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/domain/model/place.dart
  frontend/moducnu/lib/presentation/common/place_item.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/search_viewmodel.dart
Labels: 🐰 FE

#55 [Feat/FE] 검색 에러 수정 및 학교 탭 데이터 연결
  database/init-data.sql
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/api/disabled_restroom/disabled_restroom_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/domain/model/place.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/lib/domain/usecases/get_all_buildings_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_all_construction_news_usecase.dart
  frontend/moducnu/lib/presentation/map/search_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/building_info_section.dart
  frontend/moducnu/lib/presentation/school/component/building_info_viewmodel.dart
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature

#56 [Fix/FE] 컨플릭트 해결
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
Labels: 🐞 BugFix

#58 Disability Support Center API 추가 및 건물 데이터 보강
  backend/rust_server/src/handlers/disability_support_center.rs
  backend/rust_server/src/handlers/mod.rs
  backend/rust_server/src/handlers/navigation.rs
  backend/rust_server/src/main.rs
  backend/rust_server/src/models/disability_support_center.rs
  backend/rust_server/src/models/mod.rs
  backend/rust_server/src/routes/disability_support_center.rs
  backend/rust_server/src/routes/mod.rs
  database/init-data.sql
Labels: 🐧 BE, 📬 API

#57 [Feat/FE] local db(저장장소, 최근방문장소) 구현 (UI 연결은 X)
  frontend/moducnu/android/app/src/main/AndroidManifest.xml
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/lib/data/local/dao/location_data_source.dart
  frontend/moducnu/lib/data/local/entity/location_entity.dart
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature

#59 design: 건물 상세 페이지 디자인
  frontend/moducnu/lib/presentation/school/component/building_detail.dart
  frontend/moducnu/lib/presentation/school/component/building_info_section.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_detail.dart
Labels: 🐰 FE, 🐳 young, 🎨 Design

#63 휴게실, 검색 item 누르면 포커싱
  backend/rust_server/src/handlers/navigation.rs
  database/init-data.sql
  frontend/moducnu/assets/icons/ic_CurrentUser.png
  frontend/moducnu/assets/icons/ic_PlaceMarker.png
  frontend/moducnu/assets/icons/ic_PlaceMarker2.png
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/domain/model/place.dart
  frontend/moducnu/lib/presentation/common/category_list.dart
  frontend/moducnu/lib/presentation/common/custom_search_bar.dart
  frontend/moducnu/lib/presentation/common/map_component.dart
  frontend/moducnu/lib/presentation/common/place_item.dart
  frontend/moducnu/lib/presentation/common/route_finder_modal.dart
  frontend/moducnu/lib/presentation/map/map_page.dart
  frontend/moducnu/lib/presentation/map/search_page.dart
Labels: 🐰 FE, 🌟 Feature

#65 [Refactor/FE] 장애학습지원센터 building id->name 띄우도록 수정
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/di/school_di.dart
  frontend/moducnu/lib/domain/model/support_center.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/lib/domain/usecases/get_building_name_by_id_usecase.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_detail.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_viewmodel.dart
Labels: 🛠️ Refactor

#66 [Feat/FE] 장애학습지원센터 사이트 연결 구현 & 안쓰는 파일(auth관련) 삭제
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/lib/data/local/dao/.gitkeep
  frontend/moducnu/lib/data/local/entity/.gitkeep
  frontend/moducnu/lib/data/local/entity/location_data.dart
  frontend/moducnu/lib/data/mapper/auth_mapper.dart
  frontend/moducnu/lib/data/remote/api/auth/auth_api.dart
  frontend/moducnu/lib/data/remote/api/auth/auth_api.g.dart
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.dart
  frontend/moducnu/lib/data/remote/dto/auth/auth_dto.g.dart
  frontend/moducnu/lib/data/repository/auth_repositoryimpl.dart
  frontend/moducnu/lib/data/repository/construction_repositoryImpl.dart
  frontend/moducnu/lib/data/repository/school_repositoryImpl.dart
  frontend/moducnu/lib/di/auth_di.dart
  frontend/moducnu/lib/di/school_di.dart
  frontend/moducnu/lib/domain/model/User.dart
  frontend/moducnu/lib/domain/repository/auth_repository.dart
  frontend/moducnu/lib/domain/repository/construction_repository.dart
  frontend/moducnu/lib/domain/repository/school_repository.dart
  frontend/moducnu/lib/domain/usecases/auto_login_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_all_construction_news_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_all_support_centers_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_latest_construction_news_usecase.dart
  frontend/moducnu/lib/domain/usecases/login_usecase.dart
  frontend/moducnu/lib/domain/usecases/signup_usecase.dart
  frontend/moducnu/lib/presentation/auth/login_page.dart
  frontend/moducnu/lib/presentation/auth/login_viewmodel.dart
  frontend/moducnu/lib/presentation/auth/signup_page.dart
  frontend/moducnu/lib/presentation/auth/signup_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/building_detail.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_detail.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_viewmodel.dart
  frontend/moducnu/linux/flutter/generated_plugin_registrant.cc
  frontend/moducnu/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
  frontend/moducnu/windows/flutter/generated_plugin_registrant.cc
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature

#69 경사로 버튼 위치, 경사로 나누기, 문의하기
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/ios/Runner/Info.plist
  frontend/moducnu/lib/main.dart
  frontend/moducnu/lib/navigation/main_navigation_page.dart
  frontend/moducnu/lib/presentation/common/map_component.dart
  frontend/moducnu/lib/presentation/common/route_finder_modal.dart
  frontend/moducnu/lib/presentation/qa/qa_page.dart
  frontend/moducnu/lib/presentation/timetable/time_page.dart
  frontend/moducnu/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/moducnu/pubspec.lock
  frontend/moducnu/pubspec.yaml
Labels: 🐰 FE, 🦖 zungu

#70 [Feat/FE] 학교탭 내부 검색바 위치 수정, 검색 기능 구현
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/main.dart
  frontend/moducnu/lib/navigation/main_navigation_page.dart
  frontend/moducnu/lib/presentation/school/component/building_info_section.dart
  frontend/moducnu/lib/presentation/school/component/building_info_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/school_search_bar.dart
  frontend/moducnu/lib/presentation/school/school_page.dart
Labels: 🐰 FE, 🌟 Feature

#71 [Feat/FE] 건물 상세 페이지 데이터 연결
  frontend/moducnu/assets/images/.gitkeep
  frontend/moducnu/assets/images/floor1.png
  frontend/moducnu/assets/images/floor2.png
  frontend/moducnu/assets/images/floor3.png
  frontend/moducnu/assets/images/floor4.png
  frontend/moducnu/assets/images/floor5.png
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.dart
  frontend/moducnu/lib/data/remote/api/building/building_api.g.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.dart
  frontend/moducnu/lib/data/remote/dto/building/building_dto.g.dart
  frontend/moducnu/lib/data/remote/dto/disability_support_center/disability_support_center_dto.g.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/domain/model/building.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/lib/domain/usecases/get_building_detail_by_id.dart
  frontend/moducnu/lib/presentation/school/component/building_detail.dart
  frontend/moducnu/lib/presentation/school/component/building_detail_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/building_info_section.dart
  frontend/moducnu/lib/presentation/school/component/disabled_center_detail.dart
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature

#76 [Feat] 저장 기능 구현
  frontend/moducnu/ios/Podfile.lock
  frontend/moducnu/lib/data/local/dao/location_data_source.dart
  frontend/moducnu/lib/data/local/entity/location_entity.dart
  frontend/moducnu/lib/data/mapper/building_mapper.dart
  frontend/moducnu/lib/data/repository/place_repositoryImpl.dart
  frontend/moducnu/lib/di/place_di.dart
  frontend/moducnu/lib/domain/model/place.dart
  frontend/moducnu/lib/domain/repository/place_repository.dart
  frontend/moducnu/lib/domain/usecases/add_saved_location_usecase.dart
  frontend/moducnu/lib/domain/usecases/check_if_place_saved_usecase.dart
  frontend/moducnu/lib/domain/usecases/delete_saved_location_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_coordinate_by_nodeid_usecase.dart
  frontend/moducnu/lib/domain/usecases/get_saved_locations_usecase.dart
  frontend/moducnu/lib/domain/usecases/toggle_saved_location_usecase.dart
  frontend/moducnu/lib/presentation/common/custom_bottom.dart
  frontend/moducnu/lib/presentation/saved/componenet/saved_bottomsheet.dart
  frontend/moducnu/lib/presentation/saved/componenet/saved_item.dart
  frontend/moducnu/lib/presentation/saved/save_page.dart
  frontend/moducnu/lib/presentation/saved/save_viewmodel.dart
  frontend/moducnu/lib/presentation/school/component/building_detail.dart
  frontend/moducnu/lib/presentation/school/component/building_detail_viewmodel.dart
Labels: 🐰 FE, 🐢 aengzu, 🌟 Feature

#81 [BE/Deploy] backend/docker-compose.yml 수정
  backend/docker-compose.yml
Labels: 🐧 BE, 🌎 Deploy, ⚔️ Setting

#83 [Design/FE] 길찾기 경로 수정 모달창 패딩 추가
  frontend/moducnu/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  frontend/moducnu/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  frontend/moducnu/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  frontend/moducnu/lib/presentation/common/route_finder_modal.dart
Labels: 🐢 aengzu, 🎨 Design
